<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-OrderAccumulator.Worker-419bfc2c-560e-46b6-8ea4-09a410f9f49f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
    <PackageReference Include="QuickFIXn.Core" Version="1.14.1" />
    <PackageReference Include="QuickFIXn.FIX44" Version="1.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderAccumulator.Core\OrderAccumulator.Core.csproj" />
  </ItemGroup>
	
	<ItemGroup>
		<None Update="SessionConfig\fix-acceptor.cfg">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>
